//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP_CW_7902_UI.TerminalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TerminalService.ITerminalService")]
    public interface ITerminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/StartCollectingSwipes", ReplyAction="http://tempuri.org/ITerminalService/StartCollectingSwipesResponse")]
        void StartCollectingSwipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/StartCollectingSwipes", ReplyAction="http://tempuri.org/ITerminalService/StartCollectingSwipesResponse")]
        System.Threading.Tasks.Task StartCollectingSwipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/GetStatus", ReplyAction="http://tempuri.org/ITerminalService/GetStatusResponse")]
        System.Collections.Generic.Dictionary<string, string> GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/GetStatus", ReplyAction="http://tempuri.org/ITerminalService/GetStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITerminalServiceChannel : CP_CW_7902_UI.TerminalService.ITerminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalServiceClient : System.ServiceModel.ClientBase<CP_CW_7902_UI.TerminalService.ITerminalService>, CP_CW_7902_UI.TerminalService.ITerminalService {
        
        public TerminalServiceClient() {
        }
        
        public TerminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartCollectingSwipes() {
            base.Channel.StartCollectingSwipes();
        }
        
        public System.Threading.Tasks.Task StartCollectingSwipesAsync() {
            return base.Channel.StartCollectingSwipesAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
    }
}
